### PR TITLE
Dark Mode Activated

### PR DESCRIPTION
**Pull request by akshatjain-akj**
this will add dark mode to the website

### CODE REVIEW

**Comment by kirav5** [comment]
@akshatjain-akj this looks really cool few changes that would be appreciated :

1. Make The toggle button UI friendly.
2. Some sections like winner and footer have different background so it should be different in dark mode too.
3. fa-icons in landing page needs to be inverted.
4. Devfolio card should be remain white.

**Comment by akshatjain-akj** [comment]
sir i have added all the recommendations please check :)

**Comment by kirav5** [comment]
That's looking cool, well Toggling is not working on desktop site @akshatjain-akj

**Comment by akshatjain-akj** [comment]
Sir it's working I have made it in desktop view only

**Comment by akshatjain-akj** [comment]
Sir,Now its solved. please check

**Pull request merged**
